add_newline = true
continuation_prompt = "[âˆ™](bright-black) "
format = "$os$hostname$username$directory$fill $all$time\n$character\n"

[container]
format = "[$symbol ](style)"
style = "bg:#212026 fg:#000000"
symbol = " ó°–"

[directory]
format = "[ï““ $path ]($style)"
style = "bg:#000000 fg:#6dd797"
truncation_length = 3
truncation_symbol = "~/ó°‡˜/"

[git_branch]
format = "[$symbol$branch ](:$remote_branch)($style)"
style = "bg:#000000 fg:#0d9c94"
symbol = "î‚ "

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”–"

[golang]
format = "[$symbol($version) ](bg:#000000 fg:#0bc9cf)"
symbol = "î˜§ "

[hostname]
format = "[$hostname ]($style)"
ssh_only = false
style = "fg:#ef6787 bg:#000000"

[line_break]
disabled = true

[lua]
format = "[$symbol($version) ](bg:#000000 fg:#2a57cc)"
symbol = "ó°¢± "

[nix_shell]
disabled = false
format = "[ïŒ“ NIX SHELL ]($style)"
style = "bg:#000000 fg:#9d81ba"

[nodejs]
format = "[$symbol($version) ](bg:#000000 fg:#eed891)"
symbol = "î "

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bg:#000000 fg:#ef6787"

[os.symbols]
Arch = "[ïŒƒ ](fg:#0bc9cf)"
Debian = "[ïŒ†](fg:#ef6787)"
EndeavourOS = "[ïŒ¢ ](fg:#9d81ba)"
Fedora = "[ïŒŠ ](fg:color bg:#0bc9cf)"
NixOS = "[ïŒ“](fg:#f8f8f2 bg:#000000)"
SUSE = "[ïŒ” ](fg:#6dd797)"
Ubuntu = "[ïŒœ ](fg:#9d81ba"
openSUSE = "[ïŒ” ](fg:#6dd797)"

[python]
format = "[$symbol$pyenv_prefix($version)(($virtualenv)) ](bg:#000000 fg:#0d9c94)"
symbol = "îˆµ "

[time]
disabled = false
format = "[ó°”Ÿ $time ]($style)"
style = "bg:#000000 fg:#0bc9cf"
time_format = "%m-%d %R"

[username]
format = "[$user ]($style)"
show_always = true
style_user = "bg:#000000 fg:#eed891"

